/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorCuenta;

/**
 *
 * @author nicoo
 */
public class VistaCuentaProfesional  extends javax.swing.JFrame {
    private ControladorCuenta cCuenta;
    private VistaConfirmacion vConfirmacion;

    /**
     * Creates new form VistaCuentaProfesional
     */
    public VistaCuentaProfesional() {
        initComponents();
    }

    public VistaCuentaProfesional(ControladorCuenta aThis) {
        initComponents();
        cCuenta = aThis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CampoRut = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(CampoRut, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(CampoRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoRut;
    // End of variables declaration//GEN-END:variables

    public String demePacienteQM() {
        return CampoRut.getText();
    }

    public void MuestreRutInvalidoFM() {
        vConfirmacion = new VistaConfirmacion(this, true, "Rut ingresado inválido");
        if(vConfirmacion.demeEstadoQM()){
            vConfirmacion.dispose();
        }else{
            vConfirmacion.dispose();
        }
    }
}
