/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorAgendamiento;

/**
 *
 * @author nicoo
 */
public class VistaAgendamiento  extends javax.swing.JFrame{
    
    private ControladorAgendamiento cAgenda;
    private VistaConfirmacion vConfirmacion;
    
    /**
     * Creates new form VistaAgendamientoHoras
     */
    public VistaAgendamiento() {
        initComponents();
    }

    public VistaAgendamiento(ControladorAgendamiento aThis) {
        initComponents();
        cAgenda = aThis;
        ComboBoxPorfesionales.setEnabled(false);
        ComboBoxFecha.setEnabled(false);
        ComboBoxBloque.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonVolver = new javax.swing.JButton();
        BotonAgendarHorario = new javax.swing.JButton();
        PanelProfesional = new javax.swing.JPanel();
        ComboBoxPorfesionales = new javax.swing.JComboBox();
        labelSelProf = new javax.swing.JLabel();
        labelInfoProf = new javax.swing.JLabel();
        PanelHorario = new javax.swing.JPanel();
        labelHorario = new javax.swing.JLabel();
        labelSelFecha = new javax.swing.JLabel();
        labelSelBloque = new javax.swing.JLabel();
        ComboBoxBloque = new javax.swing.JComboBox();
        ComboBoxFecha = new javax.swing.JComboBox();
        PanelPaciente = new javax.swing.JPanel();
        labelHorario1 = new javax.swing.JLabel();
        labelRUT = new javax.swing.JLabel();
        CampoRut = new javax.swing.JTextField();
        labelPrioridad = new javax.swing.JLabel();
        BotonBuscarPaciente = new javax.swing.JButton();
        labelNombrePaciente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        BotonVolver.setText("Volver");
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverPressedMM(evt);
            }
        });

        BotonAgendarHorario.setText("Agendar bloque");

        PanelProfesional.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ComboBoxPorfesionales.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Omar Matus", "Rodrigo Ramírez", "Carlos Espinoza" }));

        labelSelProf.setText("Seleccione profesional");

        labelInfoProf.setText("Profesional");

        javax.swing.GroupLayout PanelProfesionalLayout = new javax.swing.GroupLayout(PanelProfesional);
        PanelProfesional.setLayout(PanelProfesionalLayout);
        PanelProfesionalLayout.setHorizontalGroup(
            PanelProfesionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProfesionalLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(labelInfoProf))
            .addGroup(PanelProfesionalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelSelProf)
                .addGap(10, 10, 10)
                .addComponent(ComboBoxPorfesionales, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelProfesionalLayout.setVerticalGroup(
            PanelProfesionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProfesionalLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(labelInfoProf)
                .addGap(6, 6, 6)
                .addGroup(PanelProfesionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelProfesionalLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(labelSelProf))
                    .addComponent(ComboBoxPorfesionales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        PanelHorario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelHorario.setText("Horario");

        labelSelFecha.setText("Seleccione fecha:");

        labelSelBloque.setText("Seleccione bloque horario:");

        javax.swing.GroupLayout PanelHorarioLayout = new javax.swing.GroupLayout(PanelHorario);
        PanelHorario.setLayout(PanelHorarioLayout);
        PanelHorarioLayout.setHorizontalGroup(
            PanelHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHorarioLayout.createSequentialGroup()
                .addGroup(PanelHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHorario)
                    .addGroup(PanelHorarioLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(labelSelFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBoxFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelSelBloque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBoxBloque, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        PanelHorarioLayout.setVerticalGroup(
            PanelHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHorarioLayout.createSequentialGroup()
                .addComponent(labelHorario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSelFecha)
                    .addComponent(labelSelBloque)
                    .addComponent(ComboBoxBloque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelPaciente.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelHorario1.setText("Paciente");

        labelRUT.setText("RUT:");

        labelPrioridad.setText("Prioridad: ");

        BotonBuscarPaciente.setText("Buscar paciente");
        BotonBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarPacientePressedMM(evt);
            }
        });

        labelNombrePaciente.setText("Nombre:");

        javax.swing.GroupLayout PanelPacienteLayout = new javax.swing.GroupLayout(PanelPaciente);
        PanelPaciente.setLayout(PanelPacienteLayout);
        PanelPacienteLayout.setHorizontalGroup(
            PanelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPacienteLayout.createSequentialGroup()
                .addComponent(labelHorario1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRUT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoRut, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNombrePaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonBuscarPaciente)
                .addContainerGap())
        );
        PanelPacienteLayout.setVerticalGroup(
            PanelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPacienteLayout.createSequentialGroup()
                .addComponent(labelHorario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRUT)
                    .addComponent(CampoRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPrioridad)
                    .addComponent(BotonBuscarPaciente)
                    .addComponent(labelNombrePaciente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelHorario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BotonAgendarHorario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonVolver))
                    .addComponent(PanelProfesional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonVolver)
                    .addComponent(BotonAgendarHorario))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonVolverPressedMM(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverPressedMM
        // TODO add your handling code here:
        cAgenda.volver();
    }//GEN-LAST:event_BotonVolverPressedMM

    private void BotonBuscarPacientePressedMM(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarPacientePressedMM
        // TODO add your handling code here:
        cAgenda.buscarPaciente();
    }//GEN-LAST:event_BotonBuscarPacientePressedMM
    
    public VistaConfirmacion getVistaConfirmacion(){
        return this.vConfirmacion;
    }
    public String demeRutCampoRut(){
        return CampoRut.getText();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgendarHorario;
    private javax.swing.JButton BotonBuscarPaciente;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JTextField CampoRut;
    private javax.swing.JComboBox ComboBoxBloque;
    private javax.swing.JComboBox ComboBoxFecha;
    private javax.swing.JComboBox ComboBoxPorfesionales;
    private javax.swing.JPanel PanelHorario;
    private javax.swing.JPanel PanelPaciente;
    private javax.swing.JPanel PanelProfesional;
    private javax.swing.JLabel labelHorario;
    private javax.swing.JLabel labelHorario1;
    private javax.swing.JLabel labelInfoProf;
    private javax.swing.JLabel labelNombrePaciente;
    private javax.swing.JLabel labelPrioridad;
    private javax.swing.JLabel labelRUT;
    private javax.swing.JLabel labelSelBloque;
    private javax.swing.JLabel labelSelFecha;
    private javax.swing.JLabel labelSelProf;
    // End of variables declaration//GEN-END:variables

    public void MuestreRutInvalidoFM() {
        vConfirmacion = new VistaConfirmacion(this, true, "Rut ingresado inválido");
        if(vConfirmacion.demeEstadoQM()){
            vConfirmacion.dispose();
        }else{
            vConfirmacion.dispose();
        }
    }

    public void MuestreNombrePacienteFM(String string) {
        labelNombrePaciente.setText(labelNombrePaciente.getText()+string);
    }

    public void MuestrePrioridadFM(int prioridad) {
        labelPrioridad.setText(labelPrioridad.getText()+String.valueOf(prioridad));
    }

    public void MuestreDeshabilitarPacienteFM() {
        //Desactiva los controles para paciente
        BotonBuscarPaciente.setEnabled(false);
        CampoRut.setEnabled(false);
        //Se activan los controles para profesionales
        ComboBoxPorfesionales.setEnabled(true);
    }
}
