/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorCuenta;
import java.awt.event.ActionEvent;

/**
 *
 * @author nicoo
 */
public class VistaCuentaFuncionario  extends javax.swing.JFrame {
    
    private ControladorCuenta cCuenta;
    private VistaConfirmacion vConf;
    private VistaConfirmacion vConfirmacion;
    /**
     * Creates new form VistaCuentaFuncionario
     */
    public VistaCuentaFuncionario() {
        initComponents();
    }

    public VistaCuentaFuncionario(ControladorCuenta aThis) {
        initComponents();
        this.cCuenta= aThis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonAgendarSesion = new javax.swing.JButton();
        BotonCerrarSesion = new javax.swing.JButton();
        BotonTalleres = new javax.swing.JButton();
        labelFuncionario = new javax.swing.JLabel();
        BotonVerFicha = new javax.swing.JButton();
        labelRUT = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelBusquedaFichas = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        CampoRut = new javax.swing.JTextField();
        labelNombreFuncionario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        BotonAgendarSesion.setText("Agendar sesión");
        BotonAgendarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgendarSesionPressedMM(evt);
            }
        });

        BotonCerrarSesion.setText("Cerrar Sesión");
        BotonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerrarSesionPressedMM(evt);
            }
        });

        BotonTalleres.setText("Talleres");
        BotonTalleres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTalleresPressedMM(evt);
            }
        });

        labelFuncionario.setText("Funcionario");

        BotonVerFicha.setText("Ver Ficha");
        BotonVerFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVerFichaPressedMM(evt);
            }
        });

        labelRUT.setText("Ingrese RUT de paciente:");

        labelBusquedaFichas.setText("Busqueda de ficha");

        labelNombreFuncionario.setText("Nombre: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 77, Short.MAX_VALUE)
                        .addComponent(BotonVerFicha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonAgendarSesion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonTalleres)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonCerrarSesion))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFuncionario)
                            .addComponent(labelBusquedaFichas)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelRUT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoRut, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelNombreFuncionario))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNombreFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(labelBusquedaFichas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRUT)
                    .addComponent(CampoRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BotonTalleres)
                        .addComponent(BotonAgendarSesion)
                        .addComponent(BotonCerrarSesion))
                    .addComponent(BotonVerFicha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonVerFichaPressedMM(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVerFichaPressedMM
        // TODO add your handling code here:
        cCuenta.abrirFicha();
    }//GEN-LAST:event_BotonVerFichaPressedMM

    private void BotonAgendarSesionPressedMM(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgendarSesionPressedMM
        // TODO add your handling code here:
        cCuenta.abrirAgendamiento();
    }//GEN-LAST:event_BotonAgendarSesionPressedMM

    private void BotonTalleresPressedMM(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTalleresPressedMM
        // TODO add your handling code here:
        vConf = new VistaConfirmacion(this, true, "Funcionalidad no implementada aún");
        if(vConf.demeEstadoQM()){
            vConf.dispose();
        }else{
            vConf.dispose();
        }
        //cCuenta.abrirTalleres();
    }//GEN-LAST:event_BotonTalleresPressedMM

    private void BotonCerrarSesionPressedMM(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerrarSesionPressedMM
        // TODO add your handling code here:
        vConf = new VistaConfirmacion(this, true, "ATENCIÓN, confirme el cierre de sesión");
        if(vConf.demeEstadoQM()){
            vConf.dispose();
            cCuenta.cerrarSesion();
        }else{
            vConf.dispose();
        }
        
    }//GEN-LAST:event_BotonCerrarSesionPressedMM
    
    public String demePacienteQM(){
        return CampoRut.getText();
    }
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgendarSesion;
    private javax.swing.JButton BotonCerrarSesion;
    private javax.swing.JButton BotonTalleres;
    private javax.swing.JButton BotonVerFicha;
    private javax.swing.JTextField CampoRut;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelBusquedaFichas;
    private javax.swing.JLabel labelFuncionario;
    private javax.swing.JLabel labelNombreFuncionario;
    private javax.swing.JLabel labelRUT;
    // End of variables declaration//GEN-END:variables

}
