/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorCuenta;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author nicoo
 */
public class VistaFicha  extends javax.swing.JFrame {

    private ControladorCuenta cCuenta;
    /**
     * Creates new form VistaFicha
     */
    public VistaFicha() {
        initComponents();
    }

    public VistaFicha(ControladorCuenta aThis) {
        initComponents();
        cCuenta = aThis;
    }
    
    //MODEL
    DefaultListModel dm = new DefaultListModel();
    
    //ADD TO LIST
    private void add(String text){
        ListaObs.setModel(dm);
        dm.addElement((text));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTelefono = new javax.swing.JLabel();
        labelEdad = new javax.swing.JLabel();
        labelCarrera = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelPaciente = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelPrioridad = new javax.swing.JLabel();
        BotonVolver = new javax.swing.JButton();
        PanelObs = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaObs = new javax.swing.JList();
        BotonEliminarObs = new javax.swing.JButton();
        labelObs = new javax.swing.JLabel();
        BotonAgregarObs = new javax.swing.JButton();
        TextComentarios = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        labelTelefono.setText("Teléfono de contacto:");

        labelEdad.setText("Edad:");

        labelCarrera.setText("Carerra:");

        labelNombre.setText("Nombre completo:");

        labelPaciente.setText("Paciente");

        labelPrioridad.setText("Prioridad:");

        BotonVolver.setText("Volver");
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverPressedMM(evt);
            }
        });

        PanelObs.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelObs.setName("PanelObservaciones"); // NOI18N

        jScrollPane2.setViewportView(ListaObs);

        BotonEliminarObs.setText("Borrar observación");
        BotonEliminarObs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarObsPressedMM(evt);
            }
        });

        labelObs.setText("Observaciones");

        BotonAgregarObs.setText("Agregar observación");
        BotonAgregarObs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarObsActionPerformed(evt);
            }
        });

        TextComentarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextComentariosActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese Aquí sus comentarios");

        javax.swing.GroupLayout PanelObsLayout = new javax.swing.GroupLayout(PanelObs);
        PanelObs.setLayout(PanelObsLayout);
        PanelObsLayout.setHorizontalGroup(
            PanelObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelObsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addGroup(PanelObsLayout.createSequentialGroup()
                        .addComponent(labelObs)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelObsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BotonAgregarObs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonEliminarObs))
                    .addComponent(TextComentarios, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(PanelObsLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelObsLayout.setVerticalGroup(
            PanelObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelObsLayout.createSequentialGroup()
                .addComponent(labelObs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonEliminarObs)
                    .addComponent(BotonAgregarObs))
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelObs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BotonVolver))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCarrera)
                            .addComponent(labelEdad)
                            .addComponent(labelTelefono)
                            .addComponent(labelPaciente))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(labelNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(labelPrioridad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCarrera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelEdad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelObs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonVolver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonVolverPressedMM(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverPressedMM
        // TODO add your handling code here:
        cCuenta.volverCuentaDesdeFicha();
    }//GEN-LAST:event_BotonVolverPressedMM

    private void BotonEliminarObsPressedMM(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarObsPressedMM
        // TODO add your handling code here:
        int index = ListaObs.getSelectedIndex();
        dm.removeElementAt(index);
       
    }//GEN-LAST:event_BotonEliminarObsPressedMM

    private void TextComentariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextComentariosActionPerformed
        TextComentarios.setText("");
    }//GEN-LAST:event_TextComentariosActionPerformed

    private void BotonAgregarObsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarObsActionPerformed

        if(TextComentarios.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Debe ingresar algun comentario.");

        }
        else{
            add(TextComentarios.getText());
            TextComentarios.setText("");
        }          
    }//GEN-LAST:event_BotonAgregarObsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarObs;
    private javax.swing.JButton BotonEliminarObs;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JList ListaObs;
    private javax.swing.JPanel PanelObs;
    private javax.swing.JTextField TextComentarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelCarrera;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelObs;
    private javax.swing.JLabel labelPaciente;
    private javax.swing.JLabel labelPrioridad;
    private javax.swing.JLabel labelTelefono;
    // End of variables declaration//GEN-END:variables
}
