/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorPrincipal;

/**
 *
 * @author nicoo
 */
public class VistaPrincipal  extends javax.swing.JFrame {
    private ControladorPrincipal cP;
    /**
     * Creates new form VistaPrincipal2
     */
    public VistaPrincipal() {
        initComponents();
    }
    
    //Constructor de VistaPrincipal con el cual se inicializa un objeto de VistaPrincipal
    public VistaPrincipal(ControladorPrincipal aThis) {
        initComponents();
        cP = aThis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelLogo = new javax.swing.JLabel();
        BotonAutenticar = new javax.swing.JButton();
        BotonRegistro = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        LabelUnidad = new javax.swing.JLabel();
        LabelUniversidad = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        LabelLogo.setText("imagen");
        LabelLogo.setToolTipText("");
        LabelLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Ayuda Psicológica USACH");
        setBounds(new java.awt.Rectangle(0, 0, 600, 600));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        setForeground(java.awt.Color.lightGray);
        setLocation(new java.awt.Point(0, 0));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 600, 600));
        setMaximumSize(null);
        setMinimumSize(null);
        setName("VistaPrincipal"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(403, 272));

        BotonAutenticar.setText("Autenticar");
        BotonAutenticar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAutenticarPressedMM(evt);
            }
        });

        BotonRegistro.setText("Registro");
        BotonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistroPressedMM(evt);
            }
        });

        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirPressedMM(evt);
            }
        });

        LabelUnidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelUnidad.setText("Unidad de Ayuda Psicológica");
        LabelUnidad.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        LabelUnidad.setName(""); // NOI18N

        LabelUniversidad.setText("Universidad de Santiago de Chile");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modelo/Logo.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(BotonAutenticar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelUnidad, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(LabelUniversidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(LabelUniversidad, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonAutenticar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Metodo que capta cuando el BotonRegistro fue presionado
    private void BotonRegistroPressedMM(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistroPressedMM
        // TODO add your handling code here:
        cP.registrar();
    }//GEN-LAST:event_BotonRegistroPressedMM

    //Metodo que capta cuando el BotonSalir fue presionado
    private void BotonSalirPressedMM(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirPressedMM
        cP.cerrar();
        
    }//GEN-LAST:event_BotonSalirPressedMM
    //Metodo que capta cuando el BotonAutenticar fue presionado
    private void BotonAutenticarPressedMM(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAutenticarPressedMM
        // TODO add your handling code here:
        cP.autenticar();
    }//GEN-LAST:event_BotonAutenticarPressedMM

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAutenticar;
    private javax.swing.JButton BotonRegistro;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JLabel LabelLogo;
    private javax.swing.JLabel LabelUnidad;
    private javax.swing.JLabel LabelUniversidad;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
